Description: >
  This template deploys an EC2 machine in a public subnet to allow an administrator to SSH into
  the private resources
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

  Keypairs:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Sub "${EnvironmentName}-JB"
      KeyType: rsa
      Tags: 
        - Key: Name 
          Value: JumpBox

  JBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow tcp to our Jump Box
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: !Sub "${EnvironmentName}-JB"
      SecurityGroupIds: 
        - !Ref JBSecurityGroup
      SubnetId:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-PUB1-SN
      Tags: 
        - Key: Name 
          Value: JumpBox
